### ISSUE TITLE
.jscsrc not loading when path has a space in it 

### ISSUE THREAD

**Issue by tbusser** [AtomLinter/linter-jscs#22]
I am using Atom on OSX 10.9.5 and `linter-jscs` is not loading my .jscsrc file in the root of my project. I think this is due to the fact that the file path has a space in one of the folder names. My project's folder is `/User/tbusser/Projects/test project` but in the Atom console I see a reference to just `/User/tbusser/Projects/test`.

![linter-error](https://cloud.githubusercontent.com/assets/5519027/4471777/a6540e48-493e-11e4-9a20-47323d401d65.jpg)

I think it is an error in `linter-jscs` because:
- `linter-jshint` has no problem reading the config file for the same project. I think this eliminates the base `linter` package as the suspect. 
- when I rename the folder of my project to eliminate the space both `linter-jscs` and `linter-jshint` report problems for my test file. I think this means the config file I have for `linter-jscs` is not the issue.

**Comment by iam4x** [comment]
@tbusser @danielsuchy Seems to be an issue with `jscs` executable itself, I added quote arround the config file should fix it.

**Comment by iam4x** [comment]
Is the issue still present with latests versions of `jscs` @tbusser ?

**Comment by tbusser** [comment]
I'm afraid the problem still exists.

This is the output I get in the console when the Linter debug setting is switched on.

```
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 command and arguments ["/Applications/Atom.app/Contents/Resources/app/apm/bin/node", "/Users/username/Dropbox/Apps/Atom/packages/linter-jscs/node_modules/jscs/bin/jscs", "-r", "checkstyle", "-c", "/Users/username/Projects/Personal/test", "project/.jscsrc", "/var/folders/g2/2kmscxhs64q_q4gnnqc2gbzr0000gn/T/AtomLinter11544-9004-1t16v4tsource.js/App.js"]
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 is node executable: true
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 beforeSpawnProcess: /Applications/Atom.app/Contents/Resources/app/apm/bin/node ["/Users/username/Dropbox/Apps/Atom/packages/linter-jscs/node_modules/jscs/bin/jscs", "-r", "checkstyle", "-c", "/Users/username/Projects/Personal/test", "project/.jscsrc", "/var/folders/g2/2kmscxhs64q_q4gnnqc2gbzr0000gn/T/AtomLinter11544-9004-1t16v4tsource.js/App.js"] Object {cwd: "/Users/username/Projects/Personal/test project/src/files/static/js"}
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 command and arguments ["/Applications/Atom.app/Contents/Resources/app/apm/bin/node", "/Users/username/Dropbox/Apps/Atom/packages/linter-jshint/node_modules/jshint/bin/jshint", "--verbose", "--extract=auto", "-c", "/Users/username/Projects/Personal/test project/.jshintrc", "/var/folders/g2/2kmscxhs64q_q4gnnqc2gbzr0000gn/T/AtomLinter11544-9004-1t16v4tsource.js/App.js"]
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 is node executable: true
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 beforeSpawnProcess: /Applications/Atom.app/Contents/Resources/app/apm/bin/node ["/Users/username/Dropbox/Apps/Atom/packages/linter-jshint/node_modules/jshint/bin/jshint", "--verbose", "--extract=auto", "-c", "/Users/username/Projects/Personal/test project/.jshintrc", "/var/folders/g2/2kmscxhs64q_q4gnnqc2gbzr0000gn/T/AtomLinter11544-9004-1t16v4tsource.js/App.js"] Object {cwd: "/Users/username/Projects/Personal/test project/src/files/static/js"}
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:19 stderr Configuration source /Users/username/Projects/Personal/test was not found.

/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 jscs returned LinterJscs {lintFile: function, buildCmd: function, updateOption: function, editor: TextEditor, beforeSpawnProcess: function…} []
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 jshint returned LinterJshint {formatShellCmd: function, editor: TextEditor, beforeSpawnProcess: function, cwd: "/Users/username/Projects/Personal/test project/src/files/static/js", subscriptions: CompositeDisposable…} []
/Users/username/Dropbox/Apps/Atom/packages/linter/lib/utils.coffee:11 IntervalMethod: debounce
```

I'm using Atom 0.196.0 on OSX 10.10.3. linter is version 0.12.1 and linter-jscs version 1.10.0.

**Comment by formula1** [comment]
FWIW jscs [uses](https://github.com/AtomLinter/linter-jscs/blob/master/lib/linter-jscs.coffee#L43) [findFile](https://github.com/AtomLinter/linter-jscs/blob/master/lib/linter-jscs.coffee#L7) from the [linter package](https://github.com/AtomLinter/Linter/blob/9cecdfc01209a7c3a0502e48d78fad01e91c5f60/lib/util.coffee#L25)

Your file may be misnamed or this may have to go up stream. This module itself is pretty simple so it may not be what is causing the issue : /

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-jscs/pull/71

**Comment by iam4x** [comment]
@steelbrain Are you sure? It's more something wrong with `findFile`.

**Comment by steelbrain** [comment]
@iam4x I suppose the rewrite is using the `atom-linter` module's `findFile` and I've wrote it with my own hands and I am sure it'll work on paths with a space in them

**Comment by iam4x** [comment]
@steelbrain :+1:
